### ISSUE TITLE
Where are the downloaded files saved?

### ISSUE THREAD

**Issue by Aayush9029** [lcharlick/DownloadManager#1]
Is there a way to access the downloaded content or save it to the files app perhaps?

**Comment by lcharlick** [comment]
The `DownloadManagerDelegate` you set should receive a [`download(_:didFinishDownloadingTo:)`](https://github.com/lcharlick/DownloadManager/blob/491353f387e857cec54f7f6700f5314662067bae/Sources/DownloadManager/DownloadManagerDelegate.swift#L34) message when a download finishes. From there you can move the file wherever you'd like (e.g. the documents directory).
